# Generated by Django 5.2.4 on 2025-07-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('movies', models.ManyToManyField(blank=True, to='movies.movie')),
            ],
        ),
    ]
