# Generated by Django 5.2.4 on 2025-07-29 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
