# Generated by Django 5.2.4 on 2025-07-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users',
        ),
    ]
